name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Nexus IQ for GitHub Actions
        uses: sonatype-nexus-community/iq-github-action@1.1.1
